version: '3.8'
services:
  web:
    network_mode: "bridge"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISCOURSE_HOSTNAME: 'discourse.nctu.me'
        DISCOURSE_DEVELOPER_EMAILS: 'blueworrybear@gmail.com'
        DISCOURSE_SMTP_ADDRESS: "smtp.sendgrid.net"
        DISCOURSE_SMTP_PORT: 2525
        DISCOURSE_SMTP_USER_NAME: apikey
        DISCOURSE_SMTP_PASSWORD: ""
        # Replace with your let's encrypt email to enable HTTPs
        LETSENCRYPT_ACCOUNT_EMAIL: 'OFF'
    image: discourse.benno
    volumes:
      - type: bind
        source: /var/discourse/shared/standalone
        target: /shared
      - type: bind
        source: /var/discourse/shared/standalone/log/var-log
        target: /var/log
    ports:
      - "80:80"
      - "443:443"
      - "2525:2525"
